# AirGradient Open Air Outdoor Monitor with CO2 and TVOC
# Model: O-1PST
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  devicename: "ag-open-air-o-1pst"
  friendly_devicename: "AG Open Air O-1PST"
  ag_esphome_config_version: 1.0.0
  add_mac_suffix: "true"  # Must have quotes around value

# Enable Home Assistant API
api:  # Add encryption key as desired

ota:  # Add password as desired

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

packages:
  board: github://MallocArray/airgradient_esphome/packages/airgradient_esp32-c3_board.yaml
  pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003t.yaml
  co2: github://MallocArray/airgradient_esphome/packages/sensor_s8.yaml
  tvoc: github://MallocArray/airgradient_esphome/packages/sensor_sgp41.yaml
  airgradient_api: github://MallocArray/airgradient_esphome/packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog: github://MallocArray/airgradient_esphome/packages/watchdog.yaml
  wifi: github://MallocArray/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://MallocArray/airgradient_esphome/packages/sensor_uptime.yaml
  safe_mode: github://MallocArray/airgradient_esphome/packages/switch_safe_mode.yaml
