# AirGradient Pro V3.3 - V4.2
# https://www.airgradient.com/open-airgradient/instructions/overview/

# Needs ESPHome 2023.7.0 or later

# Reference for substitutions: https://github.com/ajfriesen/ESPHome-AirGradient/blob/main/air-gradient-pro-diy.yaml
substitutions:
  <<: !include includes/substitutions.yaml

esphome:
  name: "${devicename}"
  friendly_name: "${upper_devicename}"
  name_add_mac_suffix: ${add_mac_suffix}  # Set to false if you don't want part of the MAC address in the name
  <<: !include includes/call_home_on_boot.yaml  # Reports to AirGradient dashboard after Wifi connected for quick validation


esp8266:
  board: d1_mini
  restore_from_flash: true  # Used to store state of display config

# Enable logging
# https://esphome.io/components/logger.html
logger:
  logs:
    component: ERROR  # Hiding warning messages about component taking a long time https://github.com/esphome/issues/issues/4717

# Enable Home Assistant API
api:

ota:

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

# The captive portal is a fallback mechanism for when connecting to the configured WiFi fails.
# https://esphome.io/components/captive_portal.html
captive_portal:

# web_server:  # Please note that enabling this component will take up a lot of memory and may decrease stability, especially on ESP8266.

http_request:
  # Used to support POST request to send data to AirGradient
  # https://esphome.io/components/http_request.html

switch:
  - <<: !include includes/switch_safe_mode.yaml
  - <<: !include includes/switch_display_temp.yaml
  - <<: !include includes/switch_upload_airgradient.yaml

# https://www.esphome-devices.com/devices/AirGradient-DIY/
# https://github.com/JacobMillward/airgradient_diy_pro_esphome/blob/main/airgradient_diy_pro.yaml

uart:
  # https://esphome.io/components/uart.html#uart
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: senseair_s8_uart

  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: pms5003_uart

i2c:
  # https://esphome.io/components/i2c.html
  sda: D2
  scl: D1
  frequency: 400kHz  # 400kHz eliminates warnings about components taking a long time other than SGP40 component: https://github.com/esphome/issues/issues/4717

sensor:
  - <<: !include includes/sensor_pms5003.yaml
  - <<: !include includes/sensor_aqi.yaml
  - <<: !include includes/sensor_s8.yaml
  - <<: !include includes/sensor_sht40.yaml
  # - <<: !include includes/sensor_sht30.yaml
  - <<: !include includes/sensor_wifi.yaml
  - <<: !include includes/sensor_uptime.yaml
  - <<: !include includes/sensor_sgp41.yaml

<<: !include includes/fonts.yaml
display:
  - <<: !include includes/display_sh1106_128_64.yaml

button:
  - <<: !include includes/button_s8_calibration.yaml
  - <<: !include includes/button_s8_calibration_enable.yaml
  - <<: !include includes/button_s8_calibration_disable.yaml
  - <<: !include includes/button_s8_calibration_interval.yaml

binary_sensor:
  - <<: !include includes/binary_sensor_config_d7.yaml

interval:
  - <<: !include includes/interval_display_page_change.yaml
  - <<: !include includes/interval_airgradient_api_post_8266.yaml
