substitutions:
  config_version: 4.0.7
  co2_offset: '0'
  name: ag-basic
  friendly_name: AG Basic
  name_add_mac_suffix: 'false'
esphome:
  name: ag-basic
  friendly_name: AG Basic
  name_add_mac_suffix: false
  project:
    name: mallocarray.airgradient
    version: 4.0.7
  min_version: 2024.6.0
  on_boot:
  - priority: 200.0
    then:
    - if:
        condition:
          switch.is_on:
            id: upload_airgradient
        then:
        - http_request.post:
            url: !lambda |-
              return "https://hw.airgradient.com/sensors/airgradient:" + get_mac_address().substr(6,11) + "/measures";
            headers:
              Content-Type: application/json
            json:
              wifi: !lambda |-
                return to_string(-50);
            capture_response: false
            max_response_buffer_size: 1000
            method: POST
  build_path: build/ag-basic
  area: ''
  platformio_options: {}
  includes: []
  libraries: []
esp8266:
  board: d1_mini
  restore_from_flash: true
  framework:
    version: 3.1.2
    source: ~3.30102.0
    platform_version: platformio/espressif8266@4.2.1
  early_pin_init: true
  board_flash_mode: dout
logger:
  logs:
    component: ERROR
  baud_rate: 115200
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  esp8266_store_log_strings_in_flash: true
uart:
- rx_pin:
    number: 2
    mode:
      input: true
      output: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  tx_pin:
    number: 0
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  baud_rate: 9600
  id: senseair_s8_uart
  rx_buffer_size: 256
  stop_bits: 1
  data_bits: 8
  parity: NONE
- rx_pin:
    number: 14
    mode:
      input: true
      output: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  tx_pin:
    number: 12
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  baud_rate: 9600
  id: pms5003_uart
  rx_buffer_size: 256
  stop_bits: 1
  data_bits: 8
  parity: NONE
i2c:
- sda: 4
  scl: 5
  frequency: 400000.0
  scan: true
wifi:
  ap:
    ap_timeout: 1min
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  passive_scan: false
  enable_on_boot: true
  use_address: ag-basic.local
captive_portal: {}
sensor:
- platform: pmsx003
  type: PMSX003
  uart_id: pms5003_uart
  pm_2_5:
    name: PM 2.5
    id: pm_2_5
    device_class: pm25
    filters:
    - lambda: !lambda |-
        float result = 0.0;
        if (x == 0.0) {
          result = 0.0;
        } else if (x < 30.0) {
          result = (0.524 * x) - (0.0862 * id(humidity_raw).state) + 5.75;
        } else if (x < 50.0) {
          result = (0.786 * (x / 20 - 3/2) + 0.524 * (1 - (x / 20 - 3/2))) * x - (0.0862 * id(humidity_raw).state) + 5.75;
        } else if (x < 210.0) {
          result = (0.786 * x) - (0.0862 * id(humidity_raw).state) + 5.75;
        } else if (x < 260.0) {
          result = (0.69 * (x / 50 - 21/5) + 0.786 * (1 - (x / 50 - 21/5))) * x - (0.0862 * id(humidity_raw).state * (1 - (x / 50 - 21/5))) + (2.966 * (x / 50 - 21/5)) + (5.75 * (1 - (x / 50 - 21/5))) + (8.84 * pow(10,-4) * pow(x,2) * (x / 50 - 21/5));
        } else {
          result = 2.966 + (0.69 * x) + (8.84 * pow(10,-4) * pow(x,2));
        }
        if (result <= 0.0) {
          return 0.0;
        } else {
          return result;
        }
    disabled_by_default: false
    force_update: false
    unit_of_measurement: µg/m³
    icon: mdi:chemical-weapon
    accuracy_decimals: 0
    state_class: measurement
  pm_1_0:
    name: PM 1.0
    id: pm_1_0
    device_class: pm1
    disabled_by_default: false
    force_update: false
    unit_of_measurement: µg/m³
    icon: mdi:chemical-weapon
    accuracy_decimals: 0
    state_class: measurement
  pm_10_0:
    name: PM 10.0
    id: pm_10_0
    device_class: pm10
    disabled_by_default: false
    force_update: false
    unit_of_measurement: µg/m³
    icon: mdi:chemical-weapon
    accuracy_decimals: 0
    state_class: measurement
  pm_0_3um:
    name: PM 0.3
    id: pm_0_3um
    filters: []
    disabled_by_default: false
    force_update: false
    unit_of_measurement: /dL
    icon: mdi:chemical-weapon
    accuracy_decimals: 0
    state_class: measurement
  update_interval: 30s
- platform: template
  name: PM 2.5 AQI
  id: pm_2_5_aqi
  update_interval: 5min
  device_class: aqi
  icon: mdi:air-filter
  accuracy_decimals: 0
  filters:
  - skip_initial: 1
  lambda: !lambda |-
    // 2024 update from EPA https://www.epa.gov/system/files/documents/2024-02/pm-naaqs-air-quality-index-fact-sheet.pdf
    // https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI
    // Borrowed from https://github.com/kylemanna/sniffer/blob/master/esphome/sniffer_common.yaml
    if (id(pm_2_5).state <= 9.0) {
    // good
    return((50.0 - 0.0) / (9.0 - 0.0) * (id(pm_2_5).state - 0.0) + 0.0);
    } else if (id(pm_2_5).state <= 35.4) {
    // moderate
    return((100.0 - 51.0) / (35.4 - 9.1) * (id(pm_2_5).state - 9.1) + 51.0);
    } else if (id(pm_2_5).state <= 55.4) {
    // usg
    return((150.0 - 101.0) / (55.4 - 35.5) * (id(pm_2_5).state - 35.5) + 101.0);
    } else if (id(pm_2_5).state <= 125.4) {
    // unhealthy
    return((200.0 - 151.0) / (125.4 - 55.5) * (id(pm_2_5).state - 55.5) + 151.0);
    } else if (id(pm_2_5).state <= 225.4) {
    // very unhealthy
    return((300.0 - 201.0) / (225.4 - 125.5) * (id(pm_2_5).state - 125.5) + 201.0);
    } else if (id(pm_2_5).state <= 325.4) {
    // hazardous
    return((500.0 - 301.0) / (325.4 - 225.5) * (id(pm_2_5).state - 225.5) + 301.0);
    } else {
    return(500);
    }
  disabled_by_default: false
  force_update: false
- platform: senseair
  co2:
    name: CO2
    id: co2
    filters:
    - skip_initial: 1
    - offset: 0.0
    disabled_by_default: false
    force_update: false
    unit_of_measurement: ppm
    icon: mdi:molecule-co2
    accuracy_decimals: 0
    device_class: carbon_dioxide
    state_class: measurement
  id: senseair_s8
  uart_id: senseair_s8_uart
  update_interval: 60s
- platform: sht3xd
  temperature:
    name: Temperature Raw
    id: temp_raw
    disabled_by_default: true
    force_update: false
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
  humidity:
    name: Humidity Raw
    id: humidity_raw
    disabled_by_default: true
    force_update: false
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    state_class: measurement
  address: 0x44
  heater_enabled: false
  update_interval: 60s
- platform: copy
  source_id: temp_raw
  name: Temperature
  id: temp
  disabled_by_default: false
  force_update: false
  unit_of_measurement: °C
  accuracy_decimals: 1
  device_class: temperature
  state_class: measurement
- platform: copy
  source_id: humidity_raw
  name: Humidity
  id: humidity
  disabled_by_default: false
  force_update: false
  unit_of_measurement: '%'
  accuracy_decimals: 1
  device_class: humidity
  state_class: measurement
- platform: wifi_signal
  name: WiFi Signal
  id: wifi_dbm
  update_interval: 60s
  disabled_by_default: false
  force_update: false
  unit_of_measurement: dBm
  accuracy_decimals: 0
  device_class: signal_strength
  state_class: measurement
  entity_category: diagnostic
- platform: uptime
  name: Uptime
  id: device_uptime
  disabled_by_default: false
  force_update: false
  unit_of_measurement: s
  icon: mdi:timer-outline
  accuracy_decimals: 0
  device_class: duration
  state_class: total_increasing
  entity_category: diagnostic
  update_interval: 60s
button:
- platform: template
  name: SenseAir S8 Calibration
  id: senseair_s8_calibrate_button
  on_press:
  - then:
    - senseair.background_calibration:
        id: senseair_s8
    - delay: 70s
    - senseair.background_calibration_result:
        id: senseair_s8
  disabled_by_default: false
- platform: template
  name: SenseAir S8 Show Calibration Interval
  id: senseair_s8_show_calibrate_interval
  on_press:
  - then:
    - senseair.abc_get_period:
        id: senseair_s8
  disabled_by_default: false
switch:
- platform: template
  name: SenseAir S8 Automatic Baseline Correction
  id: senseair_s8_abc_switch
  restore_mode: RESTORE_DEFAULT_ON
  optimistic: true
  entity_category: config
  turn_on_action:
    then:
    - senseair.abc_enable:
        id: senseair_s8
  turn_off_action:
    then:
    - senseair.abc_disable:
        id: senseair_s8
  disabled_by_default: false
  assumed_state: false
- platform: template
  name: Display Temperature in °F
  icon: mdi:thermometer
  id: display_in_f
  restore_mode: RESTORE_DEFAULT_ON
  optimistic: true
  disabled_by_default: false
  assumed_state: false
- platform: template
  name: Display Boot Page
  id: display_boot_page
  restore_mode: ALWAYS_ON
  optimistic: true
  entity_category: config
  icon: mdi:monitor
  disabled_by_default: false
  assumed_state: false
- platform: template
  name: Upload to AirGradient Dashboard
  id: upload_airgradient
  restore_mode: RESTORE_DEFAULT_OFF
  optimistic: true
  disabled_by_default: false
  assumed_state: false
font:
- file:
    family: Open Sans
    weight: 700
    italic: false
    refresh: 1d
    type: gfonts
  id: font1
  size: 22
  glyphs:
  - ' '
  - '!'
  - '"'
  - '%'
  - (
  - )
  - +
  - ','
  - '-'
  - .
  - /
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - ':'
  - '='
  - A
  - B
  - C
  - D
  - E
  - F
  - G
  - H
  - I
  - J
  - K
  - L
  - M
  - N
  - O
  - P
  - Q
  - R
  - S
  - T
  - U
  - V
  - W
  - X
  - Y
  - Z
  - _
  - a
  - b
  - c
  - d
  - e
  - f
  - g
  - h
  - i
  - j
  - k
  - l
  - m
  - n
  - o
  - p
  - q
  - r
  - s
  - t
  - u
  - v
  - w
  - x
  - y
  - z
  - °
  - ³
  - µ
  bpp: 1
display:
- platform: ssd1306_i2c
  model: SSD1306_64X48
  id: oled_display
  reset_pin:
    number: 16
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  address: 0x3C
  pages:
  - id: display_pm2
    lambda: !lambda |-
      it.print(0, 0, id(font1), "PM2");
      it.printf(64, 24, id(font1), TextAlign::TOP_RIGHT, "%.0f",id(pm_2_5).state);
  - id: display_co2
    lambda: !lambda |-
      it.print(0, 0, id(font1), "CO2");
      it.printf(64, 22, id(font1), TextAlign::TOP_RIGHT, "%.0f",id(co2).state);
  - id: display_temp
    lambda: !lambda |-
      if (id(display_in_f).state) {
          it.print(0, 0, id(font1), "°F");
          it.printf(64, 22, id(font1), TextAlign::TOP_RIGHT, "%.1f", id(temp).state*9/5+32);
        } else {
          it.print(0, 0, id(font1), "°C");
          it.printf(64, 22, id(font1), TextAlign::TOP_RIGHT, "%.1f°C", id(temp).state);
        }
  - id: display_humidity
    lambda: !lambda |-
      it.print(0, 0, id(font1), "HUM");
      it.printf(64, 22, id(font1), TextAlign::TOP_RIGHT, "%.0f%%",id(humidity).state);
  - id: boot
    lambda: !lambda |-
      it.printf(64, 0, id(font1), TextAlign::TOP_RIGHT, "%s", get_mac_address().substr(6,8).c_str());
      it.printf(64, 22, id(font1), TextAlign::TOP_RIGHT, "%s", get_mac_address().substr(9,11).c_str());
  on_page_change:
  - to: boot
    then:
    - if:
        condition:
          switch.is_off:
            id: display_boot_page
        then:
        - display.page.show_next:
            id: oled_display
        - component.update:
            id: oled_display
  auto_clear_enabled: true
  brightness: 1.0
  contrast: 1.0
  flip_x: true
  flip_y: true
  offset_x: 0
  offset_y: 0
  invert: false
  update_interval: 1s
interval:
- interval: 10s
  startup_delay: 1s
  then:
  - if:
      condition:
        switch.is_on:
          id: display_boot_page
      then:
      - switch.turn_off:
          id: display_boot_page
- interval: 5s
  then:
  - display.page.show_next:
      id: oled_display
  - component.update:
      id: oled_display
  startup_delay: 0s
- interval: 150s
  then:
  - if:
      condition:
        switch.is_on:
          id: upload_airgradient
      then:
      - http_request.post:
          url: !lambda |-
            return "https://hw.airgradient.com/sensors/airgradient:" + get_mac_address().substr(6,11) + "/measures";
          headers:
            Content-Type: application/json
          json:
            wifi: !lambda |-
              return to_string(id(wifi_dbm).state);
            rco2: !lambda |-
              return to_string(id(co2).state);
            pm01: !lambda |-
              return to_string(id(pm_1_0).state);
            pm02: !lambda |-
              return to_string(id(pm_2_5).state);
            pm10: !lambda |-
              return to_string(id(pm_10_0).state);
            pm003Count: !lambda |-
              return to_string(id(pm_0_3um).state);
            atmp: !lambda |-
              return to_string(id(temp_raw).state);
            atmpCompensated: !lambda |-
              return to_string(id(temp).state);
            rhum: !lambda |-
              return to_string(id(humidity_raw).state);
            rhumCompensated: !lambda |-
              return to_string(id(humidity).state);
            boot: !lambda |-
              return to_string(round(id(device_uptime).state/60));
          capture_response: false
          max_response_buffer_size: 1000
          method: POST
  startup_delay: 0s
http_request:
  timeout: 1s
  verify_ssl: false
  useragent: ESPHome/2024.6.3 (https://esphome.io)
  follow_redirects: true
  redirect_limit: 3
  esp8266_disable_ssl_support: false
api:
  port: 6053
  password: \033[5m''\033[6m
  reboot_timeout: 15min
ota:
- platform: esphome
  version: 2
  port: 8266
dashboard_import:
  package_import_url: github://MallocArray/airgradient_esphome/airgradient-basic.yaml
  import_full_config: false

