# Sets the full LED bar to a color relative to PM2.5 levels
# https://app.airgradient.com/dashboard/about

substitutions:
  pm_2_5_green: '0'
  pm_2_5_yellow: '11'
  pm_2_5_red: '56'
  pm_2_5_purple: '201'

interval:
  - interval: 5s
    then:
      - if:
          condition:
            light.is_on: led_strip
          then:
            - if:
                condition:
                  lambda: 'return !(isnan(id(pm_2_5).state));' # Valid data returned
                then:
                  - light.addressable_set:
                      id: led_strip
                      color_brightness: !lambda 'return ((id(led_brightness).state - (id(led_fade).state * 5)) / 100.0);'
                      range_from: 0
                      range_to: 10
                      red: !lambda 'return (id(pm_2_5).state < $pm_2_5_green) ? 0 : (id(pm_2_5).state <= $pm_2_5_yellow) ? (id(pm_2_5).state - $pm_2_5_green) / ($pm_2_5_yellow - $pm_2_5_green) : 1;'
                      green: !lambda 'return (id(pm_2_5).state < $pm_2_5_yellow) ? 1 : (id(pm_2_5).state <= $pm_2_5_red) ? 1 - (id(pm_2_5).state - $pm_2_5_yellow) / ($pm_2_5_red - $pm_2_5_yellow) : 0;'
                      blue: !lambda 'return (id(pm_2_5).state < $pm_2_5_red) ? 0 : (id(pm_2_5).state <= $pm_2_5_purple) ? (id(pm_2_5).state - $pm_2_5_red) / ($pm_2_5_purple - $pm_2_5_red) : 1;'
                  - light.addressable_set:
                      id: led_strip
                      color_brightness: !lambda 'return ((id(led_brightness).state - (id(led_fade).state * 4)) / 100.0);'
                      range_from: 1
                      range_to: 9
                      red: !lambda 'return (id(pm_2_5).state < $pm_2_5_green) ? 0 : (id(pm_2_5).state <= $pm_2_5_yellow) ? (id(pm_2_5).state - $pm_2_5_green) / ($pm_2_5_yellow - $pm_2_5_green) : 1;'
                      green: !lambda 'return (id(pm_2_5).state < $pm_2_5_yellow) ? 1 : (id(pm_2_5).state <= $pm_2_5_red) ? 1 - (id(pm_2_5).state - $pm_2_5_yellow) / ($pm_2_5_red - $pm_2_5_yellow) : 0;'
                      blue: !lambda 'return (id(pm_2_5).state < $pm_2_5_red) ? 0 : (id(pm_2_5).state <= $pm_2_5_purple) ? (id(pm_2_5).state - $pm_2_5_red) / ($pm_2_5_purple - $pm_2_5_red) : 1;'
                  - light.addressable_set:
                      id: led_strip
                      color_brightness: !lambda 'return ((id(led_brightness).state - (id(led_fade).state * 3)) / 100.0);'
                      range_from: 2
                      range_to: 8
                      red: !lambda 'return (id(pm_2_5).state < $pm_2_5_green) ? 0 : (id(pm_2_5).state <= $pm_2_5_yellow) ? (id(pm_2_5).state - $pm_2_5_green) / ($pm_2_5_yellow - $pm_2_5_green) : 1;'
                      green: !lambda 'return (id(pm_2_5).state < $pm_2_5_yellow) ? 1 : (id(pm_2_5).state <= $pm_2_5_red) ? 1 - (id(pm_2_5).state - $pm_2_5_yellow) / ($pm_2_5_red - $pm_2_5_yellow) : 0;'
                      blue: !lambda 'return (id(pm_2_5).state < $pm_2_5_red) ? 0 : (id(pm_2_5).state <= $pm_2_5_purple) ? (id(pm_2_5).state - $pm_2_5_red) / ($pm_2_5_purple - $pm_2_5_red) : 1;'
                  - light.addressable_set:
                      id: led_strip
                      color_brightness: !lambda 'return ((id(led_brightness).state - (id(led_fade).state * 2)) / 100.0);'
                      range_from: 3
                      range_to: 7
                      red: !lambda 'return (id(pm_2_5).state < $pm_2_5_green) ? 0 : (id(pm_2_5).state <= $pm_2_5_yellow) ? (id(pm_2_5).state - $pm_2_5_green) / ($pm_2_5_yellow - $pm_2_5_green) : 1;'
                      green: !lambda 'return (id(pm_2_5).state < $pm_2_5_yellow) ? 1 : (id(pm_2_5).state <= $pm_2_5_red) ? 1 - (id(pm_2_5).state - $pm_2_5_yellow) / ($pm_2_5_red - $pm_2_5_yellow) : 0;'
                      blue: !lambda 'return (id(pm_2_5).state < $pm_2_5_red) ? 0 : (id(pm_2_5).state <= $pm_2_5_purple) ? (id(pm_2_5).state - $pm_2_5_red) / ($pm_2_5_purple - $pm_2_5_red) : 1;'
                  - light.addressable_set:
                      id: led_strip
                      color_brightness: !lambda 'return ((id(led_brightness).state - (id(led_fade).state * 1)) / 100.0);'
                      range_from: 4
                      range_to: 6
                      red: !lambda 'return (id(pm_2_5).state < $pm_2_5_green) ? 0 : (id(pm_2_5).state <= $pm_2_5_yellow) ? (id(pm_2_5).state - $pm_2_5_green) / ($pm_2_5_yellow - $pm_2_5_green) : 1;'
                      green: !lambda 'return (id(pm_2_5).state < $pm_2_5_yellow) ? 1 : (id(pm_2_5).state <= $pm_2_5_red) ? 1 - (id(pm_2_5).state - $pm_2_5_yellow) / ($pm_2_5_red - $pm_2_5_yellow) : 0;'
                      blue: !lambda 'return (id(pm_2_5).state < $pm_2_5_red) ? 0 : (id(pm_2_5).state <= $pm_2_5_purple) ? (id(pm_2_5).state - $pm_2_5_red) / ($pm_2_5_purple - $pm_2_5_red) : 1;'
                  - light.addressable_set:
                      id: led_strip
                      color_brightness: !lambda 'return id(led_brightness).state / 100.0;'
                      range_from: 5
                      range_to: 5
                      red: !lambda 'return (id(pm_2_5).state < $pm_2_5_green) ? 0 : (id(pm_2_5).state <= $pm_2_5_yellow) ? (id(pm_2_5).state - $pm_2_5_green) / ($pm_2_5_yellow - $pm_2_5_green) : 1;'
                      green: !lambda 'return (id(pm_2_5).state < $pm_2_5_yellow) ? 1 : (id(pm_2_5).state <= $pm_2_5_red) ? 1 - (id(pm_2_5).state - $pm_2_5_yellow) / ($pm_2_5_red - $pm_2_5_yellow) : 0;'
                      blue: !lambda 'return (id(pm_2_5).state < $pm_2_5_red) ? 0 : (id(pm_2_5).state <= $pm_2_5_purple) ? (id(pm_2_5).state - $pm_2_5_red) / ($pm_2_5_purple - $pm_2_5_red) : 1;'
            - if:
                condition:
                  lambda: 'return (isnan(id(pm_2_5).state));'  # No data from sensor yet
                then:
                  - light.addressable_set:
                      id: led_strip
                      color_brightness: !lambda 'return id(led_brightness).state / 100.0;'
                      range_from: 0
                      range_to: 10
                      red: 0%
                      green: 0%
                      blue: 0%
