substitutions:
  pm_update_interval: "2min"

# Impliments PM2.5 correction algorithm supported by AirGradient from EPA
# https://www.airgradient.com/documentation/correction-algorithms/
# https://document.airnow.gov/airnow-fire-and-smoke-map-questions-and-answers.pdf
sensor:
  - platform: pmsx003
    # PMS5003 https://esphome.io/components/sensor/pmsx003.html
    type: PMSX003
    uart_id: pms5003_uart
    pm_2_5:
      name: "PM 2.5"
      id: pm_2_5
      device_class: pm25  # Added to report properly to HomeKit
      filters:
        - lambda: |-
            float result = 0.0;
            if (x == 0.0) {
              result = 0.0;
            } else if (x < 30.0) {
              result = (0.524 * x) - (0.0862 * id(humidity_raw).state) + 5.75;
            } else if (x < 50.0) {
              result = (0.786 * (x / 20 - 3/2) + 0.524 * (1 - (x / 20 - 3/2))) * x - (0.0862 * id(humidity_raw).state) + 5.75;
            } else if (x < 210.0) {
              result = (0.786 * x) - (0.0862 * id(humidity_raw).state) + 5.75;
            } else if (x < 260.0) {
              result = (0.69 * (x / 50 - 21/5) + 0.786 * (1 - (x / 50 - 21/5))) * x - (0.0862 * id(humidity_raw).state * (1 - (x / 50 - 21/5))) + (2.966 * (x / 50 - 21/5)) + (5.75 * (1 - (x / 50 - 21/5))) + (8.84 * pow(10,-4) * pow(x,2) * (x / 50 - 21/5));
            } else {
              result = 2.966 + (0.69 * x) + (8.84 * pow(10,-4) * pow(x,2));
            }
            if (result <= 0.0) {
              return 0.0;
            } else {
              return result;
            }
    pm_1_0:
      name: "PM 1.0"
      id: pm_1_0
      device_class: pm1  # Added to report properly to HomeKit
    pm_10_0:
      name: "PM 10.0"
      id: pm_10_0
      device_class: pm10  # Added to report properly to HomeKit
    pm_0_3um:
      name: "PM 0.3"
      id: pm_0_3um
    update_interval: $pm_update_interval


  - platform: template
    # Depends on another sensor providing an ID of pm_2_5 such as a pms5003
    name: "PM 2.5 AQI"
    id: pm_2_5_aqi
    device_class: aqi
    update_interval: 5 min
    icon: "mdi:air-filter"
    accuracy_decimals: 0
    filters:
      - skip_initial: 1  # Need valid data from PM 2.5 sensor before able to calculate
    lambda: |-
      // 2024 update from EPA https://www.epa.gov/system/files/documents/2024-02/pm-naaqs-air-quality-index-fact-sheet.pdf
      // https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI
      // Borrowed from https://github.com/kylemanna/sniffer/blob/master/esphome/sniffer_common.yaml
      if (id(pm_2_5).state <= 9.0) {
      // good
      return((50.0 - 0.0) / (9.0 - 0.0) * (id(pm_2_5).state - 0.0) + 0.0);
      } else if (id(pm_2_5).state <= 35.4) {
      // moderate
      return((100.0 - 51.0) / (35.4 - 9.1) * (id(pm_2_5).state - 9.1) + 51.0);
      } else if (id(pm_2_5).state <= 55.4) {
      // usg
      return((150.0 - 101.0) / (55.4 - 35.5) * (id(pm_2_5).state - 35.5) + 101.0);
      } else if (id(pm_2_5).state <= 125.4) {
      // unhealthy
      return((200.0 - 151.0) / (125.4 - 55.5) * (id(pm_2_5).state - 55.5) + 151.0);
      } else if (id(pm_2_5).state <= 225.4) {
      // very unhealthy
      return((300.0 - 201.0) / (225.4 - 125.5) * (id(pm_2_5).state - 125.5) + 201.0);
      } else if (id(pm_2_5).state <= 325.4) {
      // hazardous
      return((500.0 - 301.0) / (325.4 - 225.5) * (id(pm_2_5).state - 225.5) + 301.0);
      } else {
      return(500);
      }
