substitutions:
  co2_offset: '0'

sensor:
  - platform: senseair
    # SenseAir S8 https://esphome.io/components/sensor/senseair.html
    # https://senseair.com/products/size-counts/s8-lp/
    # https://climate.nasa.gov/vital-signs/carbon-dioxide/?intent=121
    # https://senseair.com/the-senseair-abc-algorithm/
    co2:
      name: "CO2"
      id: co2
      filters:
        - skip_initial: 1  # Sometimes returns 0 at first boot instead of valid data
        - offset: $co2_offset
    id: senseair_co2
    uart_id: senseair_co2_uart

button:
  # https://github.com/esphome/issues/issues/2444
  - platform: template
    name: SenseAir CO2 Calibration
    id: senseair_co2_calibrate_button
    entity_category: config
    on_press:
      then:
        - senseair.background_calibration: senseair_co2
        - delay: 70s
        - senseair.background_calibration_result: senseair_co2

  - platform: template
    # Displays the current ABC interval in the ESPhome logs to verify status
    name: SenseAir CO2 Write Calibration Interval To Log
    id: senseair_co2_abc_get_period
    entity_category: config
    on_press:
      then:
        - senseair.abc_get_period: senseair_co2

switch:
  - platform: template
    name: SenseAir CO2 Automatic Baseline Correction
    id: senseair_co2_abc_switch
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: True
    entity_category: config
    turn_on_action:
      - senseair.abc_enable: senseair_co2
    turn_off_action:
      - senseair.abc_disable: senseair_co2
