substitutions:
  co2_offset: '0'

sensor:
  - platform: senseair
    # SenseAir S8 https://esphome.io/components/sensor/senseair.html
    # https://senseair.com/products/size-counts/s8-lp/
    # https://climate.nasa.gov/vital-signs/carbon-dioxide/?intent=121
    # https://senseair.com/the-senseair-abc-algorithm/
    co2:
      name: "CO2"
      id: co2
      filters:
        - offset: $co2_offset
    id: senseair_s8
    uart_id: senseair_s8_uart

button:
  # https://github.com/esphome/issues/issues/2444
  - platform: template
    name: SenseAir S8 Calibration
    id: senseair_s8_calibrate_button
    on_press:
      then:
        - senseair.background_calibration: senseair_s8
        - delay: 70s
        - senseair.background_calibration_result: senseair_s8

  - platform: template
    # Displays the current ABC interval in the ESPhome logs to verify status
    name: SenseAir S8 Show Calibration Interval
    id: senseair_s8_show_calibrate_interval
    on_press:
      then:
        - senseair.abc_get_period: senseair_s8

switch:
  - platform: template
    name: SenseAir S8 Automatic Baseline Correction
    id: senseair_s8_abc_switch
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: True
    entity_category: config
    turn_on_action:
      - senseair.abc_enable: senseair_s8
    turn_off_action:
      - senseair.abc_disable: senseair_s8
