# https://github.com/esphome/esphome-project-template/blob/main/.github/workflows/publish-firmware.yml
name: Publish Firmware

on:
    push:

permissions:
  contents: write

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2024.12.0
    with:
      #### Modify below here to match your project ####
      files: |
        airgradient-one.yaml
        airgradient-open-air-o-1pst.yaml
      esphome-version: 2025.02.0
      combined-name: project-template
      #### Modify above here to match your project ####

      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  upload-to-release:
    name: Upload to Release
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2024.12.0
    needs:
      - build-firmware
    with:
      version: ${{ github.event.release.tag_name }}
